// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxrvmhyaysucyembonml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4cnZtaHlheXN1Y3llbWJvbm1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMDAyNjEsImV4cCI6MjA3MzY3NjI2MX0.lviNaCVQN5r0WSbgfOOzdpMmKVdNKZiHClIs7P_P6tI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});